prefix: "set -euo pipefail; "
data_dir: "data"
progress_dir: "data/progress"
env_dir: "/well/kelleher/users/uuc395/tsinfer-paper/env"
tsinfer_dir: "/well/kelleher/users/uuc395/tsinfer"


models:
  - "OutOfAfrica_4J17"

contigs:
  - chr20

samples:
  - {"CEU": 2000, "CHB": 500, "YRI": 500}

length_multipliers:
  - 1

seeds:
  - 1

versions:
  - "v0.4"
  - "v1.0"

ancestor_chunk_size: 1000

resources:
  default:
    threads: 4
    mem_mb: 16000
    time_min: 500

  intensive:
    threads: 124
    mem_mb: 500000
    time_min: 500

  generate_ancestors:
    threads: 62
    mem_mb: 250000
    time_min: 500

  process_ancestor_chunk:
    threads: 2
    mem_mb: 8000
    time_min: 500
