prefix: "set -euo pipefail; "
data_dir: "data"
progress_dir: "data/progress"
env_dir: "/well/kelleher/users/uuc395/tsinfer-paper/env"
tsinfer_dir: "/well/kelleher/users/uuc395/tsinfer"

sims:
  - model: "OutOfAfrica_4J17"
    contig: "chr20"
    interval: [1e5, 3e5]
    samples: {"CEU": 100, "CHB": 100, "YRI": 100}
    num_reps: 2
    seed: 1

versions:
  - "v0.4"
  - "v1.0"

ancestor_chunk_size: 1000

resources:
  default:
    threads: 4
    mem_mb: 16000
    time_min: 500

  intensive:
    threads: 124
    mem_mb: 500000
    time_min: 500

  generate_ancestors:
    threads: 62
    mem_mb: 250000
    time_min: 500

  process_ancestor_chunk:
    threads: 2
    mem_mb: 8000
    time_min: 500
