prefix: "set -euo pipefail; "
data_dir: "data/anc_eval"
progress_dir: "data/anc_eval/progress"
env_dir: "/well/kelleher/users/uuc395/tsinfer-paper/env"
tsinfer_dir: "/well/kelleher/users/uuc395/tsinfer"
error_probs_path: "data/external/EmpiricalErrorPlatinum1000G.csv"

sims:
  - model: "OutOfAfrica_4J17"
    contig: "chr20"
    left: 5e7
    right: 6e7
    samples: {"CEU": 2000, "CHB": 600, "YRI": 600}
    num_reps: 3
    seed: 2
  # - model: "OutOfAfrica_4J17"
  #   contig: "chr20"
  #   left: 1e6
  #   right: 2e6
  #   samples: {"CEU": 50, "CHB": 50, "YRI": 50}
  #   num_reps: 3
  #   seed: 5

error_configs:
  - genotype_errors: 'disabled'
    switch_error_rate: 0
    mispolarisation_error_rate: 0
    name: "none"
  - genotype_errors: 'enabled'
    switch_error_rate: 0
    mispolarisation_error_rate: 0
    name: "genotype"
  - genotype_errors: 'disabled'
    switch_error_rate: 5e-3
    mispolarisation_error_rate: 0
    name: "phasing"
  - genotype_errors: 'disabled'
    switch_error_rate: 0
    mispolarisation_error_rate: 1e-2
    name: "mispolarisation"

versions:
  - 0.4
  - 1.0

ancestor_chunk_size: 10000

resources:
  default:
    threads: 4
    mem_mb: 16000
    time_min: 500

  simulate:
    threads: 62
    mem_mb: 256000
    time_min: 500

  bio2zarr_convert:
    threads: 62
    mem_mb: 256000
    time_min: 500

  generate_ancestors:
    threads: 62
    mem_mb: 256000
    time_min: 500

  process_ancestor_chunk:
    threads: 1
    mem_mb: 16000
    time_min: 500
