prefix: "set -euo pipefail; "
data_dir: "data/anc_eval"
progress_dir: "data/anc_eval/progress"
env_dir: "/well/kelleher/users/uuc395/tsinfer-paper/env"
tsinfer_dir: "/well/kelleher/users/uuc395/tsinfer"
error_probs_path: "data/external/EmpiricalErrorPlatinum1000G.csv"

sims:
  - model: "OutOfAfrica_4J17"
    contig: "chr20"
    interval: [1e7, 1.5e7]
    samples: {"CEU": 1000, "CHB": 500, "YRI": 500}
    num_reps: 1
    seed: 1

genotype_errors:
#  - 'enabled'
  - 'disabled'

switch_error_rate:
  - 0
 # - 1e-3

mispolarisation_error_rate:
  - 0
#  - 1e-2

versions:
  - "0.4"
  - "1.0"

ancestor_chunk_size: 10000

resources:
  default:
    threads: 4
    mem_mb: 16000
    time_min: 500

  intensive:
    threads: 124
    mem_mb: 512000
    time_min: 500

  generate_ancestors:
    threads: 124
    mem_mb: 512000
    time_min: 500

  process_ancestor_chunk:
    threads: 1
    mem_mb: 16000
    time_min: 500
